### PR TITLE
db update

### PR DESCRIPTION
**Pull request by schutzbot**
automated db update

### CODE REVIEW

**Comment by lavocatt** [comment]
Please review each DB entry                                                 , manifest          , image-info        .
- [x] centos_8-aarch64-image_installer-boot.json                            , *not updated*     , updated           , 
- [x] centos_8-aarch64-image_installer_with_users-boot.json                 , *not updated*     , updated           , 
- [x] centos_8-aarch64-qcow2_customize-boot.json                            , *not updated*     , updated           , 
- [x] centos_8-x86_64-edge_installer-boot.json                              , updated           , *not updated*     , 
- [x] centos_8-x86_64-edge_installer_with_users-boot.json                   , updated           , *not updated*     , 
- [x] centos_8-x86_64-qcow2_customize-boot.json                             , *not updated*     , updated           , 
- [x] centos_9-aarch64-edge_commit-boot.json                                , *not updated*     , updated           , 
- [x] centos_9-aarch64-edge_installer-boot.json                             , updated           , *not updated*     , 
- [x] centos_9-aarch64-edge_installer_with_users-boot.json                  , updated           , *not updated*     , 
- [x] centos_9-aarch64-image_installer-boot.json                            , updated           , updated           , 
- [x] centos_9-aarch64-image_installer_with_users-boot.json                 , updated           , updated           , 
- [x] centos_9-aarch64-qcow2_customize-boot.json                            , *not updated*     , updated           , 
- [x] centos_9-x86_64-edge_commit-boot.json                                 , *not updated*     , updated           , 
- [x] centos_9-x86_64-edge_commit_rt-boot.json                              , *not updated*     , updated           , 
- [x] centos_9-x86_64-edge_installer-boot.json                              , updated           , *not updated*     , 
- [x] centos_9-x86_64-edge_installer_with_users-boot.json                   , updated           , *not updated*     , 
- [x] centos_9-x86_64-qcow2_customize-boot.json                             , *not updated*     , updated           , 
- [x] fedora_35-aarch64-fedora_iot_installer-boot.json                      , updated           , *not updated*     , 
- [x] fedora_35-aarch64-fedora_iot_installer_with_users-boot.json           , updated           , *not updated*     , 
- [x] fedora_35-x86_64-fedora_iot_installer-boot.json                       , updated           , *not updated*     , 
- [x] fedora_35-x86_64-fedora_iot_installer_with_users-boot.json            , updated           , *not updated*     , 
- [x] fedora_36-aarch64-fedora_iot_installer-boot.json                      , updated           , *not updated*     , 
- [x] fedora_36-aarch64-fedora_iot_installer_with_users-boot.json           , updated           , *not updated*     , 
- [x] fedora_36-aarch64-qcow2_customize-boot.json                           , *not updated*     , updated           , 
- [x] fedora_36-x86_64-fedora_iot_installer-boot.json                       , updated           , *not updated*     , 
- [x] fedora_36-x86_64-fedora_iot_installer_with_users-boot.json            , updated           , *not updated*     , 
- [x] fedora_36-x86_64-qcow2_customize-boot.json                            , *not updated*     , updated           , 
- [x] rhel_85-x86_64-azure_rhui-boot.json                                   , *not updated*     , updated           , 
- [x] rhel_86-aarch64-image_installer-boot.json                             , *not updated*     , updated           , 
- [x] rhel_86-aarch64-image_installer_with_users-boot.json                  , *not updated*     , updated           , 
- [x] rhel_86-aarch64-qcow2_customize-boot.json                             , *not updated*     , updated           , 
- [x] rhel_86-x86_64-azure_rhui-boot.json                                   , *not updated*     , updated           , 
- [x] rhel_86-x86_64-edge_installer-boot.json                               , updated           , *not updated*     , 
- [x] rhel_86-x86_64-edge_installer_with_users-boot.json                    , updated           , *not updated*     , 
- [x] rhel_86-x86_64-qcow2_customize-boot.json                              , *not updated*     , updated           , 
- [x] rhel_87-aarch64-image_installer-boot.json                             , *not updated*     , updated           , 
- [x] rhel_87-aarch64-image_installer_with_users-boot.json                  , *not updated*     , updated           , 
- [x] rhel_87-aarch64-qcow2_customize-boot.json                             , *not updated*     , updated           , 
- [x] rhel_87-x86_64-azure_rhui-boot.json                                   , *not updated*     , updated           , 
- [x] rhel_87-x86_64-edge_installer-boot.json                               , updated           , *not updated*     , 
- [x] rhel_87-x86_64-edge_installer_with_users-boot.json                    , updated           , *not updated*     , 
- [x] rhel_87-x86_64-qcow2_customize-boot.json                              , *not updated*     , updated           , 
- [x] rhel_90-aarch64-edge_commit-boot.json                                 , *not updated*     , updated           , 
- [x] rhel_90-aarch64-edge_installer-boot.json                              , updated           , *not updated*     , 
- [x] rhel_90-aarch64-edge_installer_with_users-boot.json                   , updated           , *not updated*     , 
- [x] rhel_90-aarch64-image_installer-boot.json                             , updated           , updated           , 
- [x] rhel_90-aarch64-image_installer_with_users-boot.json                  , updated           , updated           , 
- [x] rhel_90-aarch64-qcow2_customize-boot.json                             , *not updated*     , updated           , 
- [x] rhel_90-x86_64-azure_rhui-boot.json                                   , *not updated*     , updated           , 
- [x] rhel_90-x86_64-ec2_sap-boot.json                                      , *not updated*     , updated           , 
- [x] rhel_90-x86_64-edge_commit-boot.json                                  , *not updated*     , updated           , 
- [x] rhel_90-x86_64-edge_commit_rt-boot.json                               , *not updated*     , updated           , 
- [x] rhel_90-x86_64-edge_installer-boot.json                               , updated           , *not updated*     , 
- [x] rhel_90-x86_64-edge_installer_with_users-boot.json                    , updated           , *not updated*     , 
- [x] rhel_90-x86_64-qcow2_customize-boot.json                              , *not updated*     , updated           , 
- [x] rhel_91-aarch64-edge_commit-boot.json                                 , *not updated*     , updated           , 
- [x] rhel_91-aarch64-edge_installer-boot.json                              , updated           , *not updated*     , 
- [x] rhel_91-aarch64-edge_installer_with_users-boot.json                   , updated           , *not updated*     , 
- [x] rhel_91-aarch64-image_installer-boot.json                             , updated           , updated           , 
- [x] rhel_91-aarch64-image_installer_with_users-boot.json                  , updated           , updated           , 
- [x] rhel_91-aarch64-qcow2_customize-boot.json                             , *not updated*     , updated           , 
- [x] rhel_91-x86_64-azure_rhui-boot.json                                   , *not updated*     , updated           , 
- [x] rhel_91-x86_64-edge_commit-boot.json                                  , *not updated*     , updated           , 
- [x] rhel_91-x86_64-edge_commit_rt-boot.json                               , *not updated*     , updated           , 
- [x] rhel_91-x86_64-edge_installer-boot.json                               , updated           , *not updated*     , 
- [x] rhel_91-x86_64-edge_installer_with_users-boot.json                    , updated           , *not updated*     , 
- [x] rhel_91-x86_64-qcow2_customize-boot.json                              , *not updated*     , updated           ,

**Review by lavocatt — APPROVED** [review]
LGTM

**Comment by ochosi** [comment]
> 

@lavocatt This looks great! I wonder if using markdown emoji could help with the readability of updated vs. not updated, e.g. :heavy_check_mark: for not updated and :large_orange_diamond: for updated so you quickly know where to look :shrug:

**Comment by lavocatt** [comment]
Good idea. I'm working on the console version of this tool that has colors :-D I'll add emojis for the GH dump.

**Comment by lavocatt** [comment]
@ochosi that would look like something like this:

Please review each DB entry, manifest, image-info.
- [ ] centos_8-x86_64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] centos_8-x86_64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] centos_9-aarch64-edge_commit-boot, *= unchanged*, 🔁 updated.
- [ ] centos_9-aarch64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] centos_9-aarch64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] centos_9-aarch64-image_installer-boot, 🔁 updated, *= unchanged*.
- [ ] centos_9-aarch64-image_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] centos_9-x86_64-edge_commit-boot, *= unchanged*, 🔁 updated.
- [ ] centos_9-x86_64-edge_commit_rt-boot, *= unchanged*, 🔁 updated.
- [ ] centos_9-x86_64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] centos_9-x86_64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_35-aarch64-fedora_iot_installer-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_35-aarch64-fedora_iot_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_35-x86_64-fedora_iot_installer-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_35-x86_64-fedora_iot_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_36-aarch64-fedora_iot_installer-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_36-aarch64-fedora_iot_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_36-x86_64-fedora_iot_installer-boot, 🔁 updated, *= unchanged*.
- [ ] fedora_36-x86_64-fedora_iot_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_86-x86_64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_86-x86_64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_87-x86_64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_87-x86_64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_90-aarch64-edge_commit-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_90-aarch64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_90-aarch64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_90-aarch64-image_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_90-aarch64-image_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_90-x86_64-ec2_sap-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_90-x86_64-edge_commit-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_90-x86_64-edge_commit_rt-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_90-x86_64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_90-x86_64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_91-aarch64-edge_commit-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_91-aarch64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_91-aarch64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_91-aarch64-image_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_91-aarch64-image_installer_with_users-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_91-x86_64-edge_commit-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_91-x86_64-edge_commit_rt-boot, *= unchanged*, 🔁 updated.
- [ ] rhel_91-x86_64-edge_installer-boot, 🔁 updated, *= unchanged*.
- [ ] rhel_91-x86_64-edge_installer_with_users-boot, 🔁 updated, *= unchanged*.

**Pull request merged**
