### PR TITLE
Fix updating of the manifest DB

### PR DESCRIPTION
**Pull request by thozza**
https://github.com/osbuild/manifest-db/pull/103 missed the fact that the `cmd/gen-manifests` from `osbuild/images` depends on `dnf-json` installed by `osbuild-depsolve-dnf` package. Fix this now.

Example failure: https://gitlab.com/redhat/services/products/image-builder/ci/manifest-db/-/jobs/5841293230

### CODE REVIEW

**Review by lavocatt — DISMISSED** [review]
Excellent! Thanks for the fix

**Review by achilleas-k — DISMISSED** [review]
Wonderful!  Thank you.

**Review by jrusz — COMMENTED** [review]
It's failing to install on centos-stream and rhel-nightly both 8 and 9, only GA rhel are working. It seems DNF can't find new enough `osbuild-selinux` package. I would expect it to be included the osbuild repo though...

EDIT: Actually I guess it needs `selinux-policy` and `selinux-policy-targeted` in newer version, so I guess newer rpmrepo snapshots?

**Comment by jrusz** [comment]
`osbuild` repo has snaphots from `20231201`, can you try updating them here as well @thozza ?

**Comment by thozza** [comment]
> `osbuild` repo has snaphots from `20231201`, can you try updating them here as well @thozza ?

yeah, I just found out about this dependency hell :face_with_spiral_eyes:

**Comment by thozza** [comment]
I resolved the dependency issue by updating used snapshots and also cleaned up a few other things... The repo could use some more love, such as not using EOL Fedora releases, but this is out of scope for my PR...

**Review by jrusz — APPROVED** [review]
LGTM

**Pull request merged**
